<?php
/**
 * @copyright Copyright (c) 2018 Code-Source
 */
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150812074042 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE cdsrc_libraries_translatable_domain_model_abstracttranslatable (persistence_object_identifier VARCHAR(40) NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE cdsrc_libraries_translatable_domain_model_abstracttranslation (persistence_object_identifier VARCHAR(40) NOT NULL, i18nparent VARCHAR(40) DEFAULT NULL, i18nlocale VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_1E4E69EAF6DF2DC1 (i18nparent), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE cdsrc_libraries_translatable_domain_model_generictranslation (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE cdsrc_libraries_translatable_domain_model_generictranslat_606f0 (persistence_object_identifier VARCHAR(40) NOT NULL, translation VARCHAR(40) DEFAULT NULL, property VARCHAR(255) NOT NULL, vboolean TINYINT(1) DEFAULT NULL, vinteger INT DEFAULT NULL, vfloat DOUBLE PRECISION DEFAULT NULL, vstring VARCHAR(255) DEFAULT NULL, vtext LONGTEXT DEFAULT NULL, vdatetime DATETIME DEFAULT NULL, varray LONGTEXT DEFAULT NULL, objectreference VARCHAR(255) DEFAULT NULL, objectclassname VARCHAR(255) DEFAULT NULL, INDEX IDX_E50DCE00B469456F (translation), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_abstracttranslation ADD CONSTRAINT FK_1E4E69EAF6DF2DC1 FOREIGN KEY (i18nparent) REFERENCES cdsrc_libraries_translatable_domain_model_abstracttranslatable (persistence_object_identifier)");
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_generictranslation ADD CONSTRAINT FK_39E64C2947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES cdsrc_libraries_translatable_domain_model_abstracttranslation (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_generictranslat_606f0 ADD CONSTRAINT FK_E50DCE00B469456F FOREIGN KEY (translation) REFERENCES cdsrc_libraries_translatable_domain_model_generictranslation (persistence_object_identifier)");
		}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_abstracttranslation DROP FOREIGN KEY FK_1E4E69EAF6DF2DC1");
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_generictranslation DROP FOREIGN KEY FK_39E64C2947A46B0A");
		$this->addSql("ALTER TABLE cdsrc_libraries_translatable_domain_model_generictranslat_606f0 DROP FOREIGN KEY FK_E50DCE00B469456F");
		$this->addSql("DROP TABLE cdsrc_libraries_translatable_domain_model_abstracttranslatable");
		$this->addSql("DROP TABLE cdsrc_libraries_translatable_domain_model_abstracttranslation");
		$this->addSql("DROP TABLE cdsrc_libraries_translatable_domain_model_generictranslation");
		$this->addSql("DROP TABLE cdsrc_libraries_translatable_domain_model_generictranslat_606f0");
	}
}