Neos:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          -
            events: ['onFlush']
            listener: 'CDSRC\Libraries\SoftDeletable\Events\EventListener'
          -
            events: ['onFlush']
            listener: 'CDSRC\Libraries\Traceable\Events\EventListener'
        filters:
            'cdsrc.libraries.softdeletable.filter': 'CDSRC\Libraries\SoftDeletable\Filters\MarkedAsDeletedFilter'

  FluidAdaptor:
    namespaces:
      t: 'CDSRC\Libraries\Translatable\ViewHelpers'
